# This file contains values from Cookiecutter

default_context:
  project_name: "pride_colors_plotly"
  project_description: "PlotLY and matplotlib pride flag color maps and templates to make your plots proud :)"
  organization: "pride_colors_plotly"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.7
  github_name: "pride_colors_plotly"
  email: "elastufka@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
